version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        depends_on: 
            - database
        ports: 
            - 3001:3000
        volumes: 
            - .:/app
            #- gem_cache:/usr/local/bundle/gems
            #- node_modules:/app/node_modules
        env_file: .env
        environment: 
            RAILS_ENV: development
            DATABASE_NAME: $DATABASE_NAME
            DATABASE_USER: $DATABASE_USER
            DATABASE_PASSWORD: $DATABASE_PASSWORD
            DATABASE_HOST: $DATABASE_HOST
    database:
        image: postgres:latest
        env_file: .env
        environment: 
            POSTGRES_PASSWORD: $DATABASE_PASSWORD
        volumes: 
            - db_data:/var/lib/postgresql/database
            #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # #redis:
    #     image: redis:latest
    # #sidekiq:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile.dev
    #     depends_on: 
    #         - app
    #         - database
    #         - redis
    #     volumes: 
    #         - .:/app
    #         - gem_cache:/usr/local/bundle/gems
    #         - node_modules:/app.node_modules
    #     env_file: .env
    #     environment: 
    #         RAILS_ENV: development
    #     entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes: 
    gem_cache:
    node_modules:
    db_data:
